# Generated by Django 2.2.24 on 2021-06-11 22:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('AC', 'Action'), ('SE', 'Serie'), ('AD', 'Adventure'), ('DR', 'Drama'), ('CO', 'Comedy'), ('SU', 'Suspended'), ('CR', 'Crime'), ('TE', 'Terror'), ('AN', 'Animation'), ('SF', 'Science fiction')], max_length=2)),
                ('author', models.CharField(max_length=30)),
                ('production', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='movies')),
                ('duration', models.DurationField()),
                ('date_launch', models.DateField()),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
