# Generated by Django 2.2.24 on 2021-07-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210630_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='ranking_movie',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
